### ISSUE TITLE
Release winapi bump

### ISSUE THREAD

**Issue by kpcyrd** [carllerche/iovec#16]
the latest released version of iovec currently depends on winapi 0.2, while the master is already bumped to 0.3. Any chance we can get a release including this change? :)

**Comment by carllerche** [comment]
Unfortunately, bumping winapi is a breaking change. None of the downstream crates are ready for a breaking change so releasing 0.3 would not be pulled in by anything.

**Comment by infinity0** [comment]
Can you elaborate? I read somewhere else you wrote that "winapi is private in this crate" so I am confused.

Even if no downstream crates are ready to upgrade to winapi 0.3 / iovec v$next right now, if you release it today they will have less things to wait for when they are finally ready. In general in an open ecosystem you should not assume that you are in synchronous communication with all downstreams.

**Comment by infinity0** [comment]
For example, one non-obvious downstream is us the Debian project, and other distros like Fedora. If iovec v$next is released now, we can experiment with patches to existing downstream crates to make them ready for winapi 0.3 / iovec v$next. That work then benefits all of you. If the release of iovec v$next is delayed then it is less clean for us to perform this work, because we would be working against winapi 0.3 / iovec 0.1.2+backedported-commit-b90b433.

Other downstreams also include potential other crate authors building on top of iovec but haven't yet uploaded their crate to crates.io. By delaying the release of iovec you also prevent these people from upgrading to the newer APIs.

**Comment by carllerche** [comment]
Oh! You are correct... sorry about that. Honestly, if it is private, I assume it could be remeoved as a deependency all together?

**Comment by carllerche** [comment]
I'm wrong, it is used, but you are correct that it is hidden. It could probably be updated, but mio, tokio, etc... still depend on winapi 0.2.

**Comment by infinity0** [comment]
I just had a look and apart from `mio` we see the following reverse-dependencies of `iovec`:

- iovec -> bytes -> ws -> mdbook

For reference here is the mio issue: https://github.com/carllerche/mio/issues/658

Any way we (Debian) can help?

**Comment by froydnj** [comment]
> I'm wrong, it is used, but you are correct that it is hidden. It could probably be updated, but mio, tokio, etc... still depend on winapi 0.2.

It would still be nice to release an updated version of iovec so that other crates that depend on iovec could start getting their dependencies moved forward sooner rather than later.  What can be done here?

**Comment by nox** [comment]
Any news on this?

**Comment by philipktlin** [comment]
Any update?

**Comment by hrydgard** [comment]
This widely depended-on crate is still pulling in an old winapi. It's time to upgrade.

Actually the problem seems to be that iovec 0.2 is still not published on crates.io.

**Comment by atouchet** [comment]
The winapi dependency was removed in #25. This can probably be closed.
